# Vayuvahana Technologies Private Limited Vajra, AGPL-3.0 License

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../data/cifar100 # dataset root dir
train: train # train images (relative to 'path') 50000 images
val: val # val images (relative to 'path') 10000 images
test: test # test images (optional)

# Classes
names:
  0: apple
  1: aquarium_fish
  2: baby
  3: bear
  4: beaver
  5: bed
  6: bee
  7: beetle
  8: bicycle
  9: bottle
  10: bowl
  11: boy
  12: bridge
  13: bus
  14: butterfly
  15: camel
  16: can
  17: castle
  18: caterpillar
  19: cattle
  20: chair
  21: chimpanzee
  22: clock
  23: cloud
  24: cockroach
  25: couch
  26: cra
  27: crocodile
  28: cup
  29: dinosaur
  30: dolphin
  31: elephant
  32: flatfish
  33: forest
  34: fox
  35: girl
  36: hamster
  37: house
  38: kangaroo
  39: keyboard
  40: lamp
  41: lawn_mower
  42: leopard
  43: lion
  44: lizard
  45: lobster
  46: man
  47: maple_tree
  48: motorcycle
  49: mountain
  50: mouse
  51: mushroom
  52: oak_tree
  53: orange
  54: orchid
  55: otter
  56: palm_tree
  57: pear
  58: pickup_truck
  59: pine_tree
  60: plain
  61: plate
  62: poppy
  63: porcupine
  64: possum
  65: rabbit
  66: raccoon
  67: ray
  68: road
  69: rocket
  70: rose
  71: sea
  72: seal
  73: shark
  74: shrew
  75: skunk
  76: skyscraper
  77: snail
  78: snake
  79: spider
  80: squirrel
  81: streetcar
  82: sunflower
  83: sweet_pepper
  84: table
  85: tank
  86: telephone
  87: television
  88: tiger
  89: tractor
  90: train
  91: trout
  92: tulip
  93: turtle
  94: wardrobe
  95: whale
  96: willow_tree
  97: wolf
  98: woman
  99: worm

# CIFAR-100 class codes to human-readable names
map:
  class0: apple
  class1: aquarium_fish
  class2: baby
  class3: bear
  class4: beaver
  class5: bed
  class6: bee
  class7: beetle
  class8: bicycle
  class9: bottle
  class10: bowl
  class11: boy
  class12: bridge
  class13: bus
  class14: butterfly
  class15: camel
  class16: can
  class17: castle
  class18: caterpillar
  class19: cattle
  class20: chair
  class21: chimpanzee
  class22: clock
  class23: cloud
  class24: cockroach
  class25: couch
  class26: cra
  class27: crocodile
  class28: cup
  class29: dinosaur
  class30: dolphin
  class31: elephant
  class32: flatfish
  class33: forest
  class34: fox
  class35: girl
  class36: hamster
  class37: house
  class38: kangaroo
  class39: keyboard
  class40: lamp
  class41: lawn_mower
  class42: leopard
  class43: lion
  class44: lizard
  class45: lobster
  class46: man
  class47: maple_tree
  class48: motorcycle
  class49: mountain
  class50: mouse
  class51: mushroom
  class52: oak_tree
  class53: orange
  class54: orchid
  class55: otter
  class56: palm_tree
  class57: pear
  class58: pickup_truck
  class59: pine_tree
  class60: plain
  class61: plate
  class62: poppy
  class63: porcupine
  class64: possum
  class65: rabbit
  class66: raccoon
  class67: ray
  class68: road
  class69: rocket
  class70: rose
  class71: sea
  class72: seal
  class73: shark
  class74: shrew
  class75: skunk
  class76: skyscraper
  class77: snail
  class78: snake
  class79: spider
  class80: squirrel
  class81: streetcar
  class82: sunflower
  class83: sweet_pepper
  class84: table
  class85: tank
  class86: telephone
  class87: television
  class88: tiger
  class89: tractor
  class90: train
  class91: trout
  class92: tulip
  class93: turtle
  class94: wardrobe
  class95: whale
  class96: willow_tree
  class97: wolf
  class98: woman
  class99: worm